options:
  hpe3par-debug:
    type: boolean
    default: False
    description: |
      Sets debug mode to cinder 3PAR.
  driver-type:
    type: string
    default: 'fc'
    description: |
      3PAR integration accepts either FC or iSCSI backend.
      If set to 'fc', Fiber Channel will be used. Otherwise,
      iscsi is selected.
  use-multipath-image-xfer:
    type: boolean
    default: False
    description: |
      If set to True, use_multipath_image_xfer will be set.
      Multipath will be used to attach/detach volumes for volume to image and
      image to volume transfers.
  enforce-multipath-for-image-xfer:
    type: boolean
    default: False
    description: |
      If set tot True, enforce_multipath_for_image_xfer will be set.
      Multipathd will be mandatory for volume to image conversions or it will
      raise an exception.
  hpe3par-iscsi-ips:
    type: string
    default: 
    description: |
      Comma-separated list of IP:PORT to be used for the iscsi connection.
  hpe3par-iscsi-chap-enabled:
    type: boolean
    default: True
    description: |
      If iscsi enabled, this option enables CHAP authentication or not.
  hpe3par-snapshot-expiration:
    type: int
    default: -1
    description1: |
      Time in hours when a snapshot expires and is deleted.
      If set to less than 0, this config will be ignored.
  hpe3par-snapshot-retention:
    type: int
    default: -1
    description: |
      Time in hours a snapshot cannot be deleted.
      If set to less than 0, this config will be ignored
  max-over-subscription-ratio:
    type: float
    default: 20.0
    description: |
      The ratio of oversubscription when thin provisioned volumes are involved.
  reserved-percentage:
    type: int
    default: 15
    description: |
      This flag represents the percentage of reserved back-end capacity
  san-ip:
    type: string
    description: | 
      IP address of SAN controller for SSH access to the array
  san-login:
    type: string
    description: |
      Username for SAN controller for SSH access to the array
  san-password:
    type: string
    description: |
      Password for SAN controller for SSH access to the array
    default: 
  hpe3par-username:
    type: string
    description: |
      3PAR username with the 'edit' role
    default: 
  hpe3par-password:
    type: string
    description: |
      3PAR password for the user specified in hpe3par_username
    default: 
  hpe3par-api-url:
    type: string
    description: |
      3PAR WS API Server URL
    default: 
  hpe3par-cpg:
    type: string
    description: |
      3PAR CPG to use for volume creation
    default: 
  hpe3par_cpg_snap:
    type: string
    default: 
    description: |
      Sets the CPG name for the snapshot.
      If empty, use the userCPG will be used.
  hpe3par_target_nsp:
    type: string
    default: 
    description: |      
  volume-backend-name:
    type: string
    description: |
      Name to present to cinder, leave blank to use charm (or alias) name
    default: 
